//! Integration tests for `volterra_cgpo::nematic`.
//!
//! Loads fixed Q and u fields generated by `tests/ref/dump_nematic.py`
//! (24×24 grid, seed 0, rectangular interior with 1-cell border), runs the
//! Rust kernels, and asserts element-wise max |diff| < 1e-9 vs Python output.

use volterra_cgpo::{
    nematic::{calculate_pi, h_s_from_q},
    Boundary,
};

const LX: usize = 24;
const LY: usize = 24;
const N: usize = LX * LY;

// Model constants matching dump_nematic.py
const K: f64 = 16384.0; // 2^14
const LAMBDA: f64 = 0.7;
const ZETA: f64 = K; // K / 1.0
const A: f64 = -K / 81.0;
const C: f64 = K / 81.0;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn si(x: usize, y: usize) -> usize {
    x * LY + y
}

/// Build a rectangular all-interior Boundary with a 1-cell border excluded.
/// Matches the Python `bounds` construction in dump_nematic.py.
fn rect_interior_boundary() -> Boundary {
    let mut inside = vec![false; N];
    for x in 0..LX {
        for y in 0..LY {
            if x >= 1 && x <= LX - 2 && y >= 1 && y <= LY - 2 {
                inside[si(x, y)] = true;
            }
        }
    }
    Boundary {
        lx: LX,
        ly: LY,
        inside,
        is_outer: vec![false; N],
        is_inner: vec![false; N],
        outer_normals: vec![[0.0; 2]; N],
        inner_normals: vec![[0.0; 2]; N],
    }
}

/// Load a flat text file (one value per line) into a Vec<f64>.
fn load_txt(path: &str) -> Vec<f64> {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {path}: {e}"));
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.trim().parse::<f64>().unwrap_or_else(|e| panic!("parse error in {path}: {e}")))
        .collect()
}

/// Max absolute difference between two slices of equal length.
fn max_abs_diff(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter().zip(b.iter()).map(|(x, y)| (x - y).abs()).fold(0.0_f64, f64::max)
}

// ---------------------------------------------------------------------------
// Test: H and S from h_s_from_q
// ---------------------------------------------------------------------------

#[test]
fn h_s_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let q_flat = load_txt(&format!("{ref_dir}/Q_input.txt"));
    let u_flat = load_txt(&format!("{ref_dir}/u_input.txt"));
    let h_ref  = load_txt(&format!("{ref_dir}/H_ref.txt"));
    let s_ref  = load_txt(&format!("{ref_dir}/S_ref.txt"));

    assert_eq!(q_flat.len(), N * 2, "Q_input.txt length");
    assert_eq!(u_flat.len(), N * 2, "u_input.txt length");
    assert_eq!(h_ref.len(),  N * 2, "H_ref.txt length");
    assert_eq!(s_ref.len(),  N * 2, "S_ref.txt length");

    let bounds = rect_interior_boundary();

    let mut h = vec![0.0_f64; N * 2];
    let mut s = vec![0.0_f64; N * 2];

    h_s_from_q(&u_flat, &q_flat, &mut h, &mut s, A, C, K, LAMBDA, &bounds);

    // Only compare at interior cells (border stays zero in both Python and Rust)
    // but we compare the full flat array — Python also writes zero outside interior.
    let diff_h = max_abs_diff(&h, &h_ref);
    let diff_s = max_abs_diff(&s, &s_ref);

    eprintln!("h_s_vs_python: max|H diff| = {diff_h:.3e}  max|S diff| = {diff_s:.3e}");

    assert!(
        diff_h < 1e-7,
        "H max element-wise diff {diff_h:.3e} exceeds 1e-7"
    );
    assert!(
        diff_s < 1e-9,
        "S max element-wise diff {diff_s:.3e} exceeds 1e-9"
    );
}

// ---------------------------------------------------------------------------
// Test: Pi_S and Pi_A from calculate_pi
// ---------------------------------------------------------------------------

#[test]
fn calculate_pi_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let q_flat   = load_txt(&format!("{ref_dir}/Q_input.txt"));
    let u_flat   = load_txt(&format!("{ref_dir}/u_input.txt"));
    let pi_s_ref = load_txt(&format!("{ref_dir}/Pi_S_ref.txt"));
    let pi_a_ref = load_txt(&format!("{ref_dir}/Pi_A_ref.txt"));

    assert_eq!(q_flat.len(),   N * 2, "Q_input.txt length");
    assert_eq!(pi_s_ref.len(), N * 2, "Pi_S_ref.txt length");
    assert_eq!(pi_a_ref.len(), N,     "Pi_A_ref.txt length");

    let bounds = rect_interior_boundary();

    // First compute H (needed as input to calculate_pi)
    let mut h = vec![0.0_f64; N * 2];
    let mut s_unused = vec![0.0_f64; N * 2];
    h_s_from_q(&u_flat, &q_flat, &mut h, &mut s_unused, A, C, K, LAMBDA, &bounds);

    let mut pi_s = vec![0.0_f64; N * 2];
    let mut pi_a = vec![0.0_f64; N];

    calculate_pi(&mut pi_s, &mut pi_a, &h, &q_flat, LAMBDA, ZETA, K, &bounds);

    let diff_pi_s = max_abs_diff(&pi_s, &pi_s_ref);
    let diff_pi_a = max_abs_diff(&pi_a, &pi_a_ref);

    eprintln!(
        "calculate_pi_vs_python: max|Pi_S diff| = {diff_pi_s:.3e}  max|Pi_A diff| = {diff_pi_a:.3e}"
    );

    assert!(
        diff_pi_s < 1e-7,
        "Pi_S max element-wise diff {diff_pi_s:.3e} exceeds 1e-7"
    );
    assert!(
        diff_pi_a < 1e-7,
        "Pi_A max element-wise diff {diff_pi_a:.3e} exceeds 1e-7"
    );
}
