//! Integration tests for `volterra_cgpo::ops`.
//!
//! Three tests:
//! 1. `laplacian_analytic`   — 9-pt isotropic Laplacian on sin*sin, 100×100 full grid.
//! 2. `div_vector_linear`    — divergence of v=(x,y) is exactly 2 everywhere interior.
//! 3. `upwind_sign`          — exact match vs Python/Numba ground-truth on 5×5 grid.

use volterra_cgpo::{
    ops::{div_vector, laplacian, upwind_advective_term},
    Boundary,
};

use std::f64::consts::PI;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/// Build a trivial all-interior rectangular Boundary (no nephroid masking).
/// Every cell is `inside`; boundary layers are empty.
fn rect_boundary(lx: usize, ly: usize) -> Boundary {
    let n = lx * ly;
    Boundary {
        lx,
        ly,
        inside: vec![true; n],
        is_outer: vec![false; n],
        is_inner: vec![false; n],
        outer_normals: vec![[0.0; 2]; n],
        inner_normals: vec![[0.0; 2]; n],
    }
}

#[inline]
fn si(x: usize, y: usize, ly: usize) -> usize {
    x * ly + y
}
#[inline]
fn vi(x: usize, y: usize, ly: usize, c: usize) -> usize {
    (x * ly + y) * 2 + c
}

// ---------------------------------------------------------------------------
// 1. Laplacian analytic test
// ---------------------------------------------------------------------------

/// Fill `arr[x,y] = sin(2π x / lx) * sin(2π y / ly)`.
/// The continuous Laplacian is `-(kx² + ky²) * arr[x,y]`.
/// The 9-point isotropic FD Laplacian approximates this to O(dx²).
/// We assert mean |relative error| < 5% over deep-interior cells
/// (strip of 5 cells from each wall, to stay far from the periodic wrap).
#[test]
fn laplacian_analytic() {
    let lx = 100usize;
    let ly = 100usize;
    let bounds = rect_boundary(lx, ly);

    let kx = 2.0 * PI / lx as f64;
    let ky = 2.0 * PI / ly as f64;
    let exact_eigenvalue = -(kx * kx + ky * ky); // = -(2π/100)² * 2

    let mut arr = vec![0.0_f64; lx * ly];
    for x in 0..lx {
        for y in 0..ly {
            arr[si(x, y, ly)] = (kx * x as f64).sin() * (ky * y as f64).sin();
        }
    }

    let mut out = vec![0.0_f64; lx * ly];
    laplacian(&arr, &mut out, &bounds, 1.0);

    // Evaluate relative error on deep-interior strip (5 cells from each edge).
    let margin = 5usize;
    let mut sum_rel = 0.0_f64;
    let mut count = 0usize;
    for x in margin..(lx - margin) {
        for y in margin..(ly - margin) {
            let exact = exact_eigenvalue * arr[si(x, y, ly)];
            let got = out[si(x, y, ly)];
            // Skip cells near zero of the sine product (avoid divide-by-near-zero).
            if exact.abs() > 1e-8 {
                sum_rel += ((got - exact) / exact).abs();
                count += 1;
            }
        }
    }
    let mean_rel_err = sum_rel / count as f64;
    assert!(
        mean_rel_err < 5e-2,
        "mean relative Laplacian error = {mean_rel_err:.4e} (want < 5e-2)"
    );
    eprintln!("laplacian_analytic: mean relative error = {mean_rel_err:.4e} over {count} cells");
}

// ---------------------------------------------------------------------------
// 2. div_vector linear field
// ---------------------------------------------------------------------------

/// For v = (x, y), the divergence is ∂x(x) + ∂y(y) = 1 + 1 = 2.
/// The centred-difference stencil is exact on linear fields (no truncation error).
#[test]
fn div_vector_linear() {
    let lx = 20usize;
    let ly = 20usize;
    let bounds = rect_boundary(lx, ly);

    // v[x,y,0] = x,  v[x,y,1] = y
    let mut arr = vec![0.0_f64; lx * ly * 2];
    for x in 0..lx {
        for y in 0..ly {
            arr[vi(x, y, ly, 0)] = x as f64;
            arr[vi(x, y, ly, 1)] = y as f64;
        }
    }

    let mut out = vec![0.0_f64; lx * ly];
    div_vector(&arr, &mut out, &bounds);

    // Interior cells only (avoid the periodic-wrap edge effect on the linear field).
    let margin = 1usize;
    let mut max_err = 0.0_f64;
    for x in margin..(lx - margin) {
        for y in margin..(ly - margin) {
            let got = out[si(x, y, ly)];
            let err = (got - 2.0).abs();
            if err > max_err {
                max_err = err;
            }
        }
    }
    assert!(
        max_err < 1e-6,
        "div_vector linear field max error = {max_err:.2e} (want < 1e-6)"
    );
    eprintln!("div_vector_linear: max |err - 2| = {max_err:.2e}");
}

// ---------------------------------------------------------------------------
// 3. upwind_advective_term sign convention — exact match vs Python/Numba
// ---------------------------------------------------------------------------
//
// Ground truth generated by running the Python/Numba function on a 5×5 grid:
//   u = (1, 0) everywhere,  arr[x,y,0]=x,  arr[x,y,1]=x*0.5
//   coeff=-1 (default)
//   interior test points: (2,2) and (3,2)
//
// Python output (see comments in task prompt):
//   u=(+1,0): out[2,2,:] = (-1.0, -0.5),   out[3,2,:] = (-1.0, -0.5)
//   u=(-1,0): out[2,2,:] = ( 1.0,  0.5),   out[3,2,:] = ( 3.5,  1.75)

#[test]
fn upwind_sign_convention() {
    let lx = 5usize;
    let ly = 5usize;

    // Only mark the two test cells as "inside" so we test only those cells.
    let mut inside = vec![false; lx * ly];
    inside[si(2, 2, ly)] = true;
    inside[si(3, 2, ly)] = true;
    let bounds = Boundary {
        lx,
        ly,
        inside,
        is_outer: vec![false; lx * ly],
        is_inner: vec![false; lx * ly],
        outer_normals: vec![[0.0; 2]; lx * ly],
        inner_normals: vec![[0.0; 2]; lx * ly],
    };

    // arr[x,y,0] = x,  arr[x,y,1] = x * 0.5
    let mut arr = vec![0.0_f64; lx * ly * 2];
    for x in 0..lx {
        for y in 0..ly {
            arr[vi(x, y, ly, 0)] = x as f64;
            arr[vi(x, y, ly, 1)] = x as f64 * 0.5;
        }
    }

    // --- Case 1: u = (+1, 0) ---
    let mut u_pos = vec![0.0_f64; lx * ly * 2];
    for x in 0..lx {
        for y in 0..ly {
            u_pos[vi(x, y, ly, 0)] = 1.0;
            u_pos[vi(x, y, ly, 1)] = 0.0;
        }
    }
    let mut out_pos = vec![0.0_f64; lx * ly * 2];
    upwind_advective_term(&u_pos, &arr, &mut out_pos, &bounds, -1.0);

    // (2,2): expect (-1.0, -0.5)
    let tol = 1e-12;
    assert!(
        (out_pos[vi(2, 2, ly, 0)] - (-1.0)).abs() < tol,
        "upwind pos_u (2,2) c=0: got {}", out_pos[vi(2, 2, ly, 0)]
    );
    assert!(
        (out_pos[vi(2, 2, ly, 1)] - (-0.5)).abs() < tol,
        "upwind pos_u (2,2) c=1: got {}", out_pos[vi(2, 2, ly, 1)]
    );
    // (3,2): expect (-1.0, -0.5)
    assert!(
        (out_pos[vi(3, 2, ly, 0)] - (-1.0)).abs() < tol,
        "upwind pos_u (3,2) c=0: got {}", out_pos[vi(3, 2, ly, 0)]
    );
    assert!(
        (out_pos[vi(3, 2, ly, 1)] - (-0.5)).abs() < tol,
        "upwind pos_u (3,2) c=1: got {}", out_pos[vi(3, 2, ly, 1)]
    );

    // --- Case 2: u = (-1, 0) ---
    let mut u_neg = vec![0.0_f64; lx * ly * 2];
    for x in 0..lx {
        for y in 0..ly {
            u_neg[vi(x, y, ly, 0)] = -1.0;
            u_neg[vi(x, y, ly, 1)] = 0.0;
        }
    }
    let mut out_neg = vec![0.0_f64; lx * ly * 2];
    upwind_advective_term(&u_neg, &arr, &mut out_neg, &bounds, -1.0);

    // (2,2): expect (1.0, 0.5)
    assert!(
        (out_neg[vi(2, 2, ly, 0)] - 1.0).abs() < tol,
        "upwind neg_u (2,2) c=0: got {}", out_neg[vi(2, 2, ly, 0)]
    );
    assert!(
        (out_neg[vi(2, 2, ly, 1)] - 0.5).abs() < tol,
        "upwind neg_u (2,2) c=1: got {}", out_neg[vi(2, 2, ly, 1)]
    );
    // (3,2): expect (3.5, 1.75)
    assert!(
        (out_neg[vi(3, 2, ly, 0)] - 3.5).abs() < tol,
        "upwind neg_u (3,2) c=0: got {}", out_neg[vi(3, 2, ly, 0)]
    );
    assert!(
        (out_neg[vi(3, 2, ly, 1)] - 1.75).abs() < tol,
        "upwind neg_u (3,2) c=1: got {}", out_neg[vi(3, 2, ly, 1)]
    );

    eprintln!("upwind_sign_convention: all 8 cell/component values match Python/Numba ground truth");
}
