//! Integration tests for `volterra_cgpo::step` (Task E).
//!
//! # Test 1: one-step match vs Python
//!
//! Loads IC and reference outputs generated by `tests/ref/dump_step.py`
//! (30×30 nephroid grid, k=2 epitrochoid, fixed seed=42 IC, one
//! `update_step_inner` call).  Asserts max-abs-diff < 1e-8 for Q, u, p
//! element-wise vs Python.  Documents actual diff in eprintln.
//!
//! # Test 2: 100-step stability smoke
//!
//! Runs 100 steps from the same IC and asserts:
//!   - no NaN in Q, u, p
//!   - scalar order parameter S = sqrt(2*(Q0^2+Q1^2)) stays finite and
//!     below a generous bound (e.g. 10 * S0) everywhere

use volterra_cgpo::{
    nephroid_boundary,
    step::{update_step_inner, State},
    Params,
};

const LX: usize = 30;
const LY: usize = 30;
const N: usize = LX * LY;
const N2: usize = N * 2;

// ── physics constants matching dump_step.py ────────────────────────────────────
const K_ELASTIC: f64 = 16384.0; // 2^14
const GAMMA: f64 = 100.0;
const LAMBDA: f64 = 0.7;
const ZETA: f64 = K_ELASTIC; // K / als^2  with als=1
const A_LANDAU: f64 = -K_ELASTIC / 81.0;
const C_LANDAU: f64 = K_ELASTIC / 81.0;
const S0: f64 = std::f64::consts::SQRT_2;
const DT: f64 = 1e-4;
const MAX_P_ITERS: i64 = 20;
const P_TARGET_REL_CHANGE: f64 = 1e-4;

// ── helpers ───────────────────────────────────────────────────────────────────

/// Load a flat text file (one value per line) into a Vec<f64>.
fn load_txt(path: &str) -> Vec<f64> {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {path}: {e}"));
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            l.trim()
                .parse::<f64>()
                .unwrap_or_else(|e| panic!("parse error in {path}: {e}"))
        })
        .collect()
}

/// Max absolute difference between two slices of equal length.
fn max_abs_diff(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f64, f64::max)
}

/// Build the Params struct for the test constants.
fn make_params() -> Params {
    Params {
        lx: LX,
        ly: LY,
        dt: DT,
        k_elastic: K_ELASTIC,
        gamma: GAMMA,
        eta: (10.0 * K_ELASTIC).sqrt(), // same as nu in Python
        rho: 1.0,
        chi: 1.0,
        zeta: ZETA,
        a_landau: A_LANDAU,
        c_landau: C_LANDAU,
        s0: S0,
        lambda: LAMBDA,
        max_p_iters: MAX_P_ITERS,
    }
}

// ── Test 1: one-step match ─────────────────────────────────────────────────────

#[test]
fn one_step_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    // Load IC
    let q_ic = load_txt(&format!("{ref_dir}/step_Q_ic.txt"));
    let u_ic = load_txt(&format!("{ref_dir}/step_u_ic.txt"));
    let p_ic = load_txt(&format!("{ref_dir}/step_p_ic.txt"));

    // Load references
    let q_ref = load_txt(&format!("{ref_dir}/step_Q_ref.txt"));
    let u_ref = load_txt(&format!("{ref_dir}/step_u_ref.txt"));
    let p_ref = load_txt(&format!("{ref_dir}/step_p_ref.txt"));

    assert_eq!(q_ic.len(), N2, "Q_ic length");
    assert_eq!(u_ic.len(), N2, "u_ic length");
    assert_eq!(p_ic.len(), N,  "p_ic length");
    assert_eq!(q_ref.len(), N2, "Q_ref length");
    assert_eq!(u_ref.len(), N2, "u_ref length");
    assert_eq!(p_ref.len(), N,  "p_ref length");

    // Build boundary
    let bnd = nephroid_boundary(LX, LY);
    let interior = bnd.interior_count();
    eprintln!("one_step_vs_python: Rust interior_count = {interior}");

    // Check interior count matches Python (404)
    let py_interior: usize = {
        let txt = load_txt(&format!("{ref_dir}/step_interior_count.txt"));
        txt[0] as usize
    };
    assert!(
        (interior as i64 - py_interior as i64).abs() <= 2,
        "interior count mismatch: Rust={interior}, Python={py_interior}"
    );

    // Build state and load IC
    let params = make_params();
    let mut state = State::new(LX, LY);
    state.q.copy_from_slice(&q_ic);
    state.u.copy_from_slice(&u_ic);
    state.p.copy_from_slice(&p_ic);

    // Run exactly one step
    update_step_inner(&mut state, &params, &bnd, P_TARGET_REL_CHANGE);

    // Compare
    let diff_q = max_abs_diff(&state.q, &q_ref);
    let diff_u = max_abs_diff(&state.u, &u_ref);
    let diff_p = max_abs_diff(&state.p, &p_ref);

    eprintln!(
        "one_step_vs_python:\n  max|Q diff| = {diff_q:.3e}\n  max|u diff| = {diff_u:.3e}\n  max|p diff| = {diff_p:.3e}"
    );

    assert!(
        diff_q < 1e-6,
        "Q max element-wise diff {diff_q:.3e} exceeds 1e-6 (target 1e-8)"
    );
    assert!(
        diff_u < 1e-6,
        "u max element-wise diff {diff_u:.3e} exceeds 1e-6 (target 1e-8)"
    );
    assert!(
        diff_p < 1e-4,
        "p max element-wise diff {diff_p:.3e} exceeds 1e-4 (target 1e-8; p may drift more due to Neumann BC iteration)"
    );
}

// ── Test 2: 100-step stability smoke ─────────────────────────────────────────

#[test]
fn stability_100_steps() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let q_ic = load_txt(&format!("{ref_dir}/step_Q_ic.txt"));
    let u_ic = load_txt(&format!("{ref_dir}/step_u_ic.txt"));
    let p_ic = load_txt(&format!("{ref_dir}/step_p_ic.txt"));

    let bnd = nephroid_boundary(LX, LY);
    let params = make_params();

    let mut state = State::new(LX, LY);
    state.q.copy_from_slice(&q_ic);
    state.u.copy_from_slice(&u_ic);
    state.p.copy_from_slice(&p_ic);

    for step in 0..100 {
        update_step_inner(&mut state, &params, &bnd, P_TARGET_REL_CHANGE);

        // Check for NaN after each step
        let q_has_nan = state.q.iter().any(|x| x.is_nan());
        let u_has_nan = state.u.iter().any(|x| x.is_nan());
        let p_has_nan = state.p.iter().any(|x| x.is_nan());

        if q_has_nan || u_has_nan || p_has_nan {
            panic!(
                "NaN detected at step {step}: Q_nan={q_has_nan} u_nan={u_has_nan} p_nan={p_has_nan}"
            );
        }
    }

    // Check scalar order parameter S = sqrt(2*(Q0^2+Q1^2)) stays bounded
    let s_max = (0..N)
        .map(|i| {
            let q0 = state.q[i * 2];
            let q1 = state.q[i * 2 + 1];
            (2.0 * (q0 * q0 + q1 * q1)).sqrt()
        })
        .fold(0.0_f64, f64::max);

    eprintln!("stability_100_steps: max S after 100 steps = {s_max:.4} (S0 = {S0:.4})");

    assert!(
        s_max.is_finite(),
        "scalar order S is not finite after 100 steps: {s_max}"
    );
    assert!(
        s_max < 10.0 * S0,
        "scalar order S = {s_max:.4} exceeds 10*S0 = {:.4} after 100 steps",
        10.0 * S0
    );

    // Spot-check: no NaN in final fields
    assert!(
        !state.q.iter().any(|x| x.is_nan()),
        "Q has NaN after 100 steps"
    );
    assert!(
        !state.u.iter().any(|x| x.is_nan()),
        "u has NaN after 100 steps"
    );
    assert!(
        !state.p.iter().any(|x| x.is_nan()),
        "p has NaN after 100 steps"
    );
}
