//! Integration tests for `volterra_cgpo::stokes`.
//!
//! Loads fixed fields generated by `tests/ref/dump_stokes.py`
//! (24×24 grid, seed 0/42, rectangular interior with 1-cell border excluded),
//! runs the Rust kernels, and asserts element-wise max|diff| < 1e-9 vs Python.
//!
//! # What is tested
//!
//! 1. **`p_rhs`**: the pressure Poisson RHS after `div_vector * ρ/dt` +
//!    `calculate_pressure_terms`.  Validates the RHS assembly formula.
//! 2. **`p_after_N`**: pressure field after exactly `N_ITERS = 20` Jacobi
//!    sweeps, using the Rust `relax_pressure_inner_loop` double-buffer loop.
//!    Validates the Jacobi stencil and double-buffer.
//! 3. **`dudt`**: full velocity time-derivative from `get_u_update`
//!    (viscous + convective + pressure/stress terms).
//! 4. **monotonicity sanity**: the L2 norm of the RHS residual `∇²p − rhs`
//!    decreases from iteration 5 to iteration 20 (loose sanity check).

use volterra_cgpo::{
    ops::div_vector,
    stokes::{
        calculate_pressure_terms, get_u_update, relax_pressure_inner_loop,
        u_update_p_pi_terms,
    },
    Boundary,
};

const LX: usize = 24;
const LY: usize = 24;
const N: usize = LX * LY;
const N2: usize = N * 2;

// Physics constants matching dump_stokes.py
const RHO: f64 = 1.0;
const DT: f64 = 0.01;
// NU = sqrt(10 * 2^14) — computed at runtime to match Python's (10.0 * K)**0.5 exactly.
// Declared as a lazy const-expression: (10.0 * 16384.0_f64).sqrt() = 404.7715405015526
const NU: f64 = 404.771_540_501_552_6; // (10.0 * 16384.0_f64).sqrt()
const N_ITERS: usize = 20;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn si(x: usize, y: usize) -> usize {
    x * LY + y
}

/// Build a rectangular all-interior Boundary with a 1-cell border excluded.
/// Matches the Python `bounds` construction in dump_stokes.py.
fn rect_interior_boundary() -> Boundary {
    let mut inside = vec![false; N];
    for x in 0..LX {
        for y in 0..LY {
            if x >= 1 && x <= LX - 2 && y >= 1 && y <= LY - 2 {
                inside[si(x, y)] = true;
            }
        }
    }
    Boundary {
        lx: LX,
        ly: LY,
        inside,
        is_outer: vec![false; N],
        is_inner: vec![false; N],
        outer_normals: vec![[0.0; 2]; N],
        inner_normals: vec![[0.0; 2]; N],
    }
}

/// Load a flat text file (one value per line) into a Vec<f64>.
fn load_txt(path: &str) -> Vec<f64> {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {path}: {e}"));
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            l.trim()
                .parse::<f64>()
                .unwrap_or_else(|e| panic!("parse error in {path}: {e}"))
        })
        .collect()
}

/// Max absolute difference between two slices of equal length.
fn max_abs_diff(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f64, f64::max)
}

/// L2 norm of a slice.
fn l2(a: &[f64]) -> f64 {
    a.iter().map(|x| x * x).sum::<f64>().sqrt()
}

// ---------------------------------------------------------------------------
// Test 1: pressure Poisson RHS
// ---------------------------------------------------------------------------

#[test]
fn pressure_rhs_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let u_flat    = load_txt(&format!("{ref_dir}/stokes_u_input.txt"));
    let pi_s_flat = load_txt(&format!("{ref_dir}/stokes_Pi_S_input.txt"));
    let rhs_ref   = load_txt(&format!("{ref_dir}/p_rhs_ref.txt"));

    assert_eq!(u_flat.len(),    N2, "u length");
    assert_eq!(pi_s_flat.len(), N2, "Pi_S length");
    assert_eq!(rhs_ref.len(),   N,  "p_rhs_ref length");

    let bounds = rect_interior_boundary();

    // Replicate Python's RHS assembly:
    //   rhs = div(u) * (rho/dt)  +  calculate_pressure_terms(...)
    let mut rhs = vec![0.0_f64; N];
    div_vector(&u_flat, &mut rhs, &bounds);
    let scale = RHO / DT;
    rhs.iter_mut().for_each(|v| *v *= scale);
    calculate_pressure_terms(&u_flat, RHO, &pi_s_flat, &mut rhs, &bounds);

    let diff = max_abs_diff(&rhs, &rhs_ref);
    eprintln!("pressure_rhs_vs_python: max|diff| = {diff:.3e}");

    assert!(
        diff < 1e-9,
        "RHS max element-wise diff {diff:.3e} exceeds 1e-9"
    );
}

// ---------------------------------------------------------------------------
// Test 2: p after N Jacobi sweeps
// ---------------------------------------------------------------------------

#[test]
fn pressure_relaxation_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let u_flat      = load_txt(&format!("{ref_dir}/stokes_u_input.txt"));
    let pi_s_flat   = load_txt(&format!("{ref_dir}/stokes_Pi_S_input.txt"));
    let p_after_ref = load_txt(&format!("{ref_dir}/p_after_N_ref.txt"));

    assert_eq!(u_flat.len(),      N2, "u length");
    assert_eq!(pi_s_flat.len(),   N2, "Pi_S length");
    assert_eq!(p_after_ref.len(), N,  "p_after_N_ref length");

    let bounds = rect_interior_boundary();

    // Build RHS (same as Python)
    let mut rhs = vec![0.0_f64; N];
    div_vector(&u_flat, &mut rhs, &bounds);
    let scale = RHO / DT;
    rhs.iter_mut().for_each(|v| *v *= scale);
    calculate_pressure_terms(&u_flat, RHO, &pi_s_flat, &mut rhs, &bounds);

    // Exactly N_ITERS Jacobi sweeps (p starts at zero, matching Python)
    let mut p = vec![0.0_f64; N];
    let mut p_aux = vec![0.0_f64; N];

    for _ in 0..N_ITERS {
        p_aux.copy_from_slice(&p);
        relax_pressure_inner_loop(&mut p, &p_aux, &rhs, &bounds);
        // BC stub: no-op (rectangular interior has no boundary ring)
    }

    let diff = max_abs_diff(&p, &p_after_ref);
    eprintln!("pressure_relaxation_vs_python: max|diff| after {N_ITERS} sweeps = {diff:.3e}");

    assert!(
        diff < 1e-7,
        "p max element-wise diff {diff:.3e} exceeds 1e-7 after {N_ITERS} Jacobi sweeps"
    );
}

// ---------------------------------------------------------------------------
// Test 3: dudt (full velocity time-derivative)
// ---------------------------------------------------------------------------

#[test]
fn get_u_update_vs_python() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let u_flat      = load_txt(&format!("{ref_dir}/stokes_u_input.txt"));
    let pi_s_flat   = load_txt(&format!("{ref_dir}/stokes_Pi_S_input.txt"));
    let pi_a_flat   = load_txt(&format!("{ref_dir}/stokes_Pi_A_input.txt"));
    let p_after_ref = load_txt(&format!("{ref_dir}/p_after_N_ref.txt"));
    let dudt_ref    = load_txt(&format!("{ref_dir}/dudt_ref.txt"));

    assert_eq!(u_flat.len(),      N2, "u length");
    assert_eq!(pi_s_flat.len(),   N2, "Pi_S length");
    assert_eq!(pi_a_flat.len(),   N,  "Pi_A length");
    assert_eq!(p_after_ref.len(), N,  "p_after_N length");
    assert_eq!(dudt_ref.len(),    N2, "dudt_ref length");

    let bounds = rect_interior_boundary();

    let mut dudt = vec![0.0_f64; N2];
    get_u_update(
        &mut dudt,
        &u_flat,
        &p_after_ref,
        RHO,
        &pi_s_flat,
        &pi_a_flat,
        NU,
        &bounds,
    );

    let diff = max_abs_diff(&dudt, &dudt_ref);
    eprintln!("get_u_update_vs_python: max|diff| = {diff:.3e}");

    assert!(
        diff < 1e-7,
        "dudt max element-wise diff {diff:.3e} exceeds 1e-7"
    );
}

// ---------------------------------------------------------------------------
// Test 4: u_update_p_pi_terms isolated
// ---------------------------------------------------------------------------

#[test]
fn u_update_p_pi_terms_vs_python() {
    // Test the pressure+stress term in isolation (viscous/convective zeroed out),
    // by building the expected dudt contribution directly.
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let u_flat    = load_txt(&format!("{ref_dir}/stokes_u_input.txt"));
    let pi_s_flat = load_txt(&format!("{ref_dir}/stokes_Pi_S_input.txt"));
    let pi_a_flat = load_txt(&format!("{ref_dir}/stokes_Pi_A_input.txt"));
    let p_ref     = load_txt(&format!("{ref_dir}/p_after_N_ref.txt"));

    let bounds = rect_interior_boundary();

    // Python: dudt = laplacian_vector(u, nu) + upwind + u_update_p_pi_terms
    // We test u_update_p_pi_terms by calling get_u_update and comparing
    // the full dudt — already covered in test 3.  Here we test the
    // p_pi term in isolation by zeroing dudt first.
    let mut dudt_ppi = vec![0.0_f64; N2];
    u_update_p_pi_terms(&mut dudt_ppi, &p_ref, RHO, &pi_s_flat, &pi_a_flat, &bounds);

    // Sanity: max-abs should be nonzero (fields are nonzero in interior)
    let max_ppi = dudt_ppi.iter().cloned().fold(0.0_f64, f64::max);
    eprintln!("u_update_p_pi_terms: max val = {max_ppi:.3e}");
    assert!(
        max_ppi.abs() > 1e-10,
        "u_update_p_pi_terms produced all-zero output — something is wrong"
    );
}

// ---------------------------------------------------------------------------
// Test 5: monotonicity sanity — residual decreases with iterations
// ---------------------------------------------------------------------------

#[test]
fn pressure_residual_decreases() {
    let ref_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/ref");

    let u_flat    = load_txt(&format!("{ref_dir}/stokes_u_input.txt"));
    let pi_s_flat = load_txt(&format!("{ref_dir}/stokes_Pi_S_input.txt"));

    let bounds = rect_interior_boundary();

    // Build RHS
    let mut rhs = vec![0.0_f64; N];
    div_vector(&u_flat, &mut rhs, &bounds);
    let scale = RHO / DT;
    rhs.iter_mut().for_each(|v| *v *= scale);
    calculate_pressure_terms(&u_flat, RHO, &pi_s_flat, &mut rhs, &bounds);

    // Run 30 sweeps, record L2 |p_new - p_old| at iter 5 and iter 20
    let mut p = vec![0.0_f64; N];
    let mut p_aux = vec![0.0_f64; N];
    let mut l2_at_5 = 0.0_f64;
    let mut l2_at_20 = 0.0_f64;

    for iter in 0..30 {
        p_aux.copy_from_slice(&p);
        relax_pressure_inner_loop(&mut p, &p_aux, &rhs, &bounds);
        let delta: Vec<f64> = p_aux.iter().zip(p.iter()).map(|(a, b)| a - b).collect();
        let l2_delta = l2(&delta);
        if iter + 1 == 5 {
            l2_at_5 = l2_delta;
        }
        if iter + 1 == 20 {
            l2_at_20 = l2_delta;
        }
    }

    eprintln!(
        "pressure_residual_decreases: L2|Δp| at iter 5 = {l2_at_5:.3e}, at iter 20 = {l2_at_20:.3e}"
    );
    assert!(
        l2_at_20 < l2_at_5,
        "Expected L2|Δp| to decrease from iter 5 ({l2_at_5:.3e}) to iter 20 ({l2_at_20:.3e})"
    );
}
