[package]
name = "volterra-py"
description = "Python bindings for the volterra active nematics simulation library"
version.workspace   = true
edition.workspace   = true
rust-version.workspace = true
license.workspace   = true
repository.workspace = true
readme.workspace     = true

# cdylib is required for PyO3 extension modules.
[lib]
name = "volterra"
crate-type = ["cdylib"]

[dependencies]
volterra-core   = { workspace = true }
volterra-fd = { workspace = true }
volterra-braid  = { workspace = true }
cartan-geo      = { workspace = true }
pyo3            = { workspace = true, features = ["extension-module"] }
numpy           = { workspace = true }
